name: release-please

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

      - name: Checkout
        uses: actions/checkout@v6
        if: ${{ steps.release.outputs.release_created }}

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          run_install: false
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24.18.0
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
        if: ${{ steps.release.outputs.release_created }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        if: ${{ steps.release.outputs.release_created }}

      - name: Publish to NPM
        run: npm publish
        if: ${{ steps.release.outputs.release_created }}
